{% set name = "copilotkit" %}
{% set version = "1.51.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/CopilotKit/CopilotKit/archive/v{{ version }}.tar.gz
  sha256: e23c7e73e178396b13869f7ccc7aef0c8360b1cbe661333440199f59db2a2bec

build:
  noarch: python
  script: {{ PYTHON }} -m pip install sdk-python/ -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }}
    - langgraph >=0.3.25,<1.1.0
    - langchain >=0.3.0
    - ag-ui-langgraph >=0.0.23
    - fastapi >=0.115.0,<0.116.0
    - partialjson >=0.0.8,<0.0.9
    - toml >=0.10.2,<0.11.0

test:
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  license: MIT
  license_file:
    - LICENSE
  home: https://github.com/CopilotKit/CopilotKit
  summary: "CopilotKit is an open-source framework for building AI copilots that assist users in various tasks by leveraging large language models and other AI technologies."

extra:
  recipe-maintainers:
    - rxm7706
